export const PATH = {
  login: "/login",
  register: "/register",
  userInfo: "/thong-tin-tai-khoan",
  ManagerAdmin: "/Admin",
  roomDetail: "/room-detail/:roomId",
  roomList: "/room-list/:listId",
  booking: "/booking/:roomId",
  binhLuan: "/binhLuan",
  listUser: "/Admin/danhSachThanhVien",
  addUser: "/Admin/taoTaiKhoan",
  locationList: "/Admin/danhSachVitri",
  addLocation: "/Admin/themVitri",
  roomDs: "/Admin/danhSachPhong",
  addRoom: "/Admin/themPhong",
  commentList: "/Admin/danhSachBinhLuan",
  datPhongList: "/Admin/datPhong",
  addDatPhong: "/Admin/addDatPhong",
};
